trigger:
  batch: true
  branches:
    include:
      - PHP-7.4
      - master
  paths:
    exclude:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS

jobs:
  - template: .azure/macos/job.yml
    parameters:
      configurationName: 'MacOS / PHP 7.4'
      phpVersion: '7.4.9'
      configurationParameters: '--enable-debug --disable-maintainer-zts'
  - template: .azure/macos/job.yml
    parameters:
      configurationName: 'MacOS / PHP 7.3'
      phpVersion: '7.3.21'
      configurationParameters: '--enable-debug --disable-maintainer-zts'
