parameters:
  configurationName: ''
  configurationParameters: ''

jobs:
  - job: ${{ parameters.configurationName }}
    pool:
      vmImage: 'macOS-10.14'
    steps:
    - template: brew.yml
    - template: php.yml
    - script: |
        export PATH="/usr/local/bin:$PATH"
        phpize && ./configure && make clean && make all && make install
      displayName: 'Compile Xdebug'
    - template: test.yml
      parameters:
        configurationName: ${{ parameters.configurationName }}
    - template: test.yml
      parameters:
        configurationName: ${{ parameters.configurationName }}
        runTestsName: 'OpCache'
        runTestsParameters: -d zend_extension=opcache.so -d opcache.enable_cli=1 -d opcache.protect_memory=1
